// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "dataprovider.dblp.enable": boolean;
      "dataprovider.dblp.apiKey": string;
      "updateStrategy": string;
    };
  }
}
